sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '0.12'
  - v4
  - stable
after_success:
  - 'travis-after-all && npm run semantic-release'
env:
  global:
    - secure: fIqSK7Lz9gNnaBxKhEy52JMtcTjYxDe5AaitvF3bZPgBPvdno7CWsvOGGuc0DtO2Rc5prPPa8d422eUmvEgBStFZwXQZBm+E+RJqXzz/Y4RSkY97LYr3ukx3kjGv+yviJTNL0b5NCb7qxsII3EwC32esf2w5JB56qhh1kxZ5xADKX162bFWoznQAjgdSKeRGBFRmjhKcn4eBz1U4L62yHQFIAs6Et5AnTGC8hiTRHI1Sml9+t6GCq8KvBJbTMkahJcrW08fASvS40UQyFQX13ZgkAN8N4xWPuZ7wqJuMkOdRAbMhbzyCP9cHOdaDdHd7lmQJsaT2Q0VEp5rrFMsS1cEwn3wOQpR2vJChgRGd9tOuupjOkfwjF9brVf4byE6XTgFxt+SmkH2ReitaerFfl7pUfwweCDzMSD+TTFgqkKaPKtljJyeme1vGsPHPOuuN/dzDyPUAe7lzyVCUplzKN+Bf+bTOR19kO3vzutXvIKY8PPc8P1m3I3FAyZQH2j3JVlzP2hR8W0uBs4JdqFNw+7bvss1zPYZqz8JJrc2OswLGjqv/gld7gegW9oI6+xcLSw+3I9HUeajN5XU5QPI42w4OTQgMmBI8Joa4RY2jqyHffHTum0OhaIWZsr8ws9DasqwxfSRjWQ+LRytlJD22T0/dToMSc+MpRy2OdKsLl6k=
    - secure: y9jpCA/4X0hvErIHVq7z9uB6KYwiO7h84Pt2RsovLOUogKO0vhTmCQ9tYlHXY0D/XlbCMRuRlNYR6OURkZK6wtSOI6qyOXcX8iMzLq3H7QY10CUeNv5L3gKPMGmnDpfY5BDXTmy1RaMayIj8PLJgl93fBEcS4yMeDkFCICZkgjiAeTDguJE17VgdX9vBrIyORwzrhiufK8suGbI60VvJJU7t7D9mff9IV9WUNqHVICK2o4SAZLnHyhDwUjfd1cwC4LGlROKLQ9EyPDo5A4yVm/oegZNQuY2Y6ytPf3ZdayvhxZ/nX3OHWvdYuWDcIVlBeH5G8qa2RI62CiH+XfJ8z4RUCL5j7mKdgoyvZ1d/59AbcygyJBL2+U8XuQ0xCWDah3PYkhaiNH3+TA627qqlAXMRXrw9fqoFjkmKMNC+MM6a8eJg+XcfB/+TC5Sc17k/3UdKW/Y0Njn4VPp/91pHtfH1DQI0s4OT9oAZHeQ7mOLGXa/Am1iwudnjNoD89DEoU09Et7Zt3ZtNFZ8jVCmxzL1sH6H8Gc8lPV4awcYrY6SckjaSkqfLcynOnJDmny6rcV+2qcLT4fWkLlVClQ8Sym2j3IO+2vO2eKovoap5vifLXw0eRH4hR2TLRXm0C4jHGfoZnZUMntT5E2lxaeUdTenhSlLnZ9gsLrFxmpmBnq8=
